trigger: none  # No automatic trigger. Use `main` if you want to trigger on push

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: ADFRepo
    type: github
    name: BharaniBK/adf2
    ref: refs/heads/adf_publish
    endpoint: github.com_Bharanibk   

variables:
  resourceGroupName: 'stage'
  dataFactoryName: 'adfstage5005'
  location: 'East US'  # or the region of your staging ADF


steps:
- checkout: ADFRepo
  clean: true

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy ADF ARM Template to Staging'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRM-Bharani'
    subscriptionId: 'bec6e1a4-6737-494d-83d7-0bf6b538a400'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: 'ARMTemplateForFactory.json'
    csmParametersFile: 'ARMTemplateParametersForFactory.json'
    overrideParameters: >
      -factoryName $(dataFactoryName)
    deploymentMode: 'Incremental'
